### ISSUE TITLE
NTRU now in C#

### ISSUE THREAD

**Issue by Steppenwolfe65** [tbuktu/ntru#3]
Hi, 
I put this library into C# (hope you don't mind). Project is here: 
https://github.com/Steppenwolfe65/NTRU-Sharp
Thanks so much for all of your hard work on this great project.
if you have any questions for me: develop@vtdev.com

John

**Comment by tbuktu** [comment]
Cool, thanks for letting me know!

**Comment by Steppenwolfe65** [comment]
A couple of questions..Do you see any particular place where code may benefit from parallelism?If using a 1024 bit digest for IGF and mask, with appropriate parameters, is 512 bit security attainable/practical?
Thanks,John 


     On Friday, April 10, 2015 3:50 PM, Tim Buktu <notifications@github.com> wrote:
   

 Closed #3.—

**Comment by tbuktu** [comment]
The parts that benefit most from parallelization are multiplication of polynomials and SHA computation. The [C implementation](https://github.com/tbuktu/libntru) does this using SIMD instructions.

512 bit security shouldn't be a problem but like you said, you need the right parameters. [This](https://github.com/NTRUOpenSourceProject/ntru-params) might help get you started, and you'll probably want to read some of the literature.

**Comment by Steppenwolfe65** [comment]
I did see some spots where yield, concurrency, and even parallel loops might work well, I plan to revisit the project and write some optimizations in a few weeks.. (doing McEliece now)
As for increasing security strength; this is what I thought. The code may need some adjustment, and parameters will need to be estimated, but otherwise.. should be ok

Thanks

**Comment by Steppenwolfe65** [comment]
A couple more questions then I'm outta your hair..
I'd like to consolidate the constructors with a productform boolean rather than 2 different constructors. How are you deriving df1-2-3? For example EES1087EP2 has df 120, product is 8, 8 and 11; what is the formula for deriving the product form numbers?

My other question regards the licence; I plan to add my version to CEX, (a little crypto library I am writing), though CEX is currently licensed as MIT. I plan to use a dual license included with the distribution, GPLv3 for NTRU, MIT for the rest, while adding the GPL license header to each public NTRU file. Is that enough, do I need to add the patent notice, and what about the FOSS exception, does that apply given it is based on your distribution?

You were right about params being the sticking point btw.. I emailed the guy who posted the params test code, he believes a lattice problem of that complexity (512 bits) probably doesn't exist.. but at least the digest is no longer a limiting factor, should someone want to experiment.

Anyways, thanks for all your help..

**Comment by tbuktu** [comment]
No worries.

The df values for the product-form versions of EES1087EP2, etc. I figured out using some inequality from a paper, but I don't know that those values are optimal. There is no reason to use N=1087 or higher for product-form parameter sets, anyway, because the N=743 parameter set has the same security strength (256 bits), it's more efficient, and most importantly it's an "official" parameter set from the reference implementation.

About the license: My code is under a BSD license which is similar to MIT. Unless you incorporated other code, you have the option of using BSD for NTRU and there is no need for a FOSS exception. The patent notice should be fine the way you have it (i.e. same as mine, it's what the patent holder asked for back then).

**Comment by Steppenwolfe65** [comment]
Thanks Tim..
So, do you think I should default the APR2011743FAST? 
The problem I have is that at least some of the parameter fields should be secret, (like db, shouldn't that be a ranged random length?) .
So it seems there has to be some sort of secret negotiation between nodes..
I might use NTRU as a KEM wrapped in McEliece, or look at implementing NTRU-KE.
I'm reading through OpenPGP right now to see exactly what they're doing, (but most of it isn't required, because what I need is strictly n2n like voice or teleconference, with no need for interoperability or complex message exchanges; so goal is security+simplicity). If you have any implementation recommendations.. please let me know.
