### ISSUE TITLE
Benchmarks

### ISSUE THREAD

**Issue by snugglebear** [tbuktu/ntru#5]
I have some questions about the Benchmark program that comes with the Java NTRU library.  How did you determine how many repetitions to do for each algorithm?  Also, what do the ECC algorithms actually do for encryption/decryption?  I have run the Benchmark on two Samsung mobile devices using a console app in Android to run it, and the ECC algorithms seem to outperform NTRU for key generation but not for encryption/decryption.  But I don't really understand what is actually going on when running encryption and decryption for ECC.  Please explain it to me.

Thanks.

**Comment by tbuktu** [comment]
Does [this](https://github.com/tbuktu/ntru/issues/2) help?

**Comment by snugglebear** [comment]
Hi, thanks for responding, I appreciate you taking some of your time to help me.

I read that link before, and I think I kind of get it now that I read it again.  Since ECDH is Diffie-Hellman it can't really be compared to NTRU for encryption/decryption, right?

Most importantly for me, the benchmark performance image at http://tbuktu.github.io/ntru/ shows much higher operations per second for most of the algorithms than what I get with your code or the official implementation at https://github.com/NTRUOpenSourceProject/ntru-crypto on my system.  I used Benchmark.java from your code and I modified Benchmark.java to work with the official (reference) implementation to do benchmarks for that as well.  I'm on a quad core intel core i7 2.3ghz, while you did your experiment on a core i3 3.1ghz.  NTRU-439 (which I'm assuming is similar to what you used for NTRU at a security level of 128) only gave 290 operations/sec for key generation with your implementation.  With the reference implementation it was only 52 operations per second for the same algorithm (different parameter set, ees449ep1 because 439 wasn't available, should give similar results right?), again for key generation.  Your results show at least a couple thousand operations per second for the reference implementation for key generation at 128-bit security.  Likewise, the other numbers were much slower than your results.  I might be doing something wrong so please inform me if you think that might be the case.

Lastly, how did you choose the number of iterations to use in each benchmark?  Some of the time consuming RSA benchmarks are repeated only a few times while others are repeated thousands of times.  I guess since RSA is much slower it would take forever if you did thousands of iterations, which is probably why you set those to do only a few iterations.  But even ECDH and NTRU use different numbers of iterations compared to each other.  Did you just roughly estimate how may repetitions should be done based on some rule of thumb?

**Comment by tbuktu** [comment]
You're right in that comparing key exchange to encryption is apples-to-oranges. But it's possible to do key exchange with a public-key encryption primitive and vice versa, and that is a comparison that makes sense I think. It's still going to be unfair to one of the two primitives of course because extra work is required for the emulation.

The benchmark chart at https://tbuktu.github.io/ntru/ is for the C implementation which is faster. The Java implementation isn't nearly as optimized. I think I used to have Java benchmarks on the web page before the C implementation existed. You might be able to find them in the Git history.

The number of iterations aren't based on a formula or anything, I simply picked them so the running times were roughly the same for each algorithm on that machine.

**Comment by snugglebear** [comment]
So even "ntru-ref" is a C version?

**Comment by tbuktu** [comment]
Yes, they are all C implementations.

**Comment by snugglebear** [comment]
I don't get the same performance in libntru that you got in your benchmarks.  I have a core i7 2.3GHz laptop.  Here are my numbers:

Testing parameter set ees401ep1... kg 745us (1342 ops/sec), e 118us (8474 ops/sec), d 207us (4830 ops/sec), 	 pk 557, sk 81, ct 552 bytes
Testing parameter set ees449ep1... kg 908us (1101 ops/sec), e 177us (5649 ops/sec), d 260us (3846 ops/sec), 	 pk 623, sk 90, ct 618 bytes
Testing parameter set ees677ep1... kg 1848us (541 ops/sec), e 242us (4132 ops/sec), d 445us (2247 ops/sec), 	 pk 936, sk 136, ct 931 bytes
Testing parameter set ees1087ep2... kg 3898us (256 ops/sec), e 293us (3412 ops/sec), d 553us (1808 ops/sec), 	 pk 1500, sk 218, ct 1495 bytes
Testing parameter set ees541ep1... kg 1208us (827 ops/sec), e 71us (14084 ops/sec), d 124us (8064 ops/sec), 	 pk 749, sk 109, ct 744 bytes
Testing parameter set ees613ep1... kg 1658us (603 ops/sec), e 102us (9803 ops/sec), d 159us (6289 ops/sec), 	 pk 848, sk 123, ct 843 bytes
Testing parameter set ees887ep1... kg 2791us (358 ops/sec), e 179us (5586 ops/sec), d 320us (3125 ops/sec), 	 pk 1225, sk 178, ct 1220 bytes
Testing parameter set ees1171ep1... kg 4863us (205 ops/sec), e 291us (3436 ops/sec), d 532us (1879 ops/sec), 	 pk 1616, sk 235, ct 1611 bytes
Testing parameter set ees659ep1... kg 1612us (620 ops/sec), e 71us (14084 ops/sec), d 117us (8547 ops/sec), 	 pk 912, sk 95, ct 907 bytes
Testing parameter set ees761ep1... kg 2057us (486 ops/sec), e 89us (11235 ops/sec), d 147us (6802 ops/sec), 	 pk 1052, sk 105, ct 1047 bytes
Testing parameter set ees1087ep1... kg 3865us (258 ops/sec), e 172us (5813 ops/sec), d 301us (3322 ops/sec), 	 pk 1500, sk 174, ct 1495 bytes
Testing parameter set ees1499ep1... kg 7823us (127 ops/sec), e 277us (3610 ops/sec), d 511us (1956 ops/sec), 	 pk 2067, sk 218, ct 2062 bytes
Testing parameter set ees401ep2... kg 579us (1727 ops/sec), e 34us (29411 ops/sec), d 52us (19230 ops/sec), 	 pk 557, sk 50, ct 552 bytes
Testing parameter set ees439ep1... kg 665us (1503 ops/sec), e 36us (27777 ops/sec), d 57us (17543 ops/sec), 	 pk 609, sk 50, ct 604 bytes
Testing parameter set ees593ep1... kg 1192us (838 ops/sec), e 58us (17241 ops/sec), d 92us (10869 ops/sec), 	 pk 821, sk 70, ct 816 bytes
Testing parameter set ees743ep1... kg 1881us (531 ops/sec), e 85us (11764 ops/sec), d 141us (7092 ops/sec), 	 pk 1027, sk 93, ct 1022 bytes
Testing parameter set ees443ep1... kg 681us (1468 ops/sec), e 39us (25641 ops/sec), d 58us (17241 ops/sec), 	 pk 615, sk 50, ct 610 bytes
Testing parameter set ees587ep1... kg 1206us (829 ops/sec), e 59us (16949 ops/sec), d 95us (10526 ops/sec), 	 pk 813, sk 70, ct 808 bytes

According to GeekBench my Core i7 is faster than the 1.6GHz Xeon used in your benchmarks so I don't know why I'm getting worse results, do you have any explanation on why the performance is not as good on my end?

**Comment by tbuktu** [comment]
From the output, it looks like you're not using libntru but the reference implementation which is slower.
